WIP: Act 0.1 release
ethereum/fv-blog pull request #7
Opened 2021-08-03 17:24 UTC by d-xo

Still pretty rough, and the Coq section is missing, but I thought it was worth putting up to get some feedback already.

2021-08-05 18:52 UTC, d-xo commented
Still wanna make a few more passes over this and improve the language, as well as fill out the example output and figure out syntax highlighting, but I think that I'm generally happy with the content.

@endorphin, it would be awesome if you had a moment to read over the [Coq section](https://github.com/ethereum/fv-blog/blob/act-0.1/_posts/2021-08-03-act-0.1.md#coq-export), I'm pretty sure there are some inaccuracies or instances of imprecise language that could be cleaned up.

2021-08-09 12:10 UTC, MrChico commented on _posts/2021-08-03-act-0.1.md
> +chain between this specification and an implementation of the spec in EVM bytecode.
```suggestion
development teams to prove properties against a high level specification, which can then either be used "upwards" to prove more higher level properties or "downwards" to demonstrate that an implementation in EVM bytecode conforms to the spec.
```

2021-08-09 12:10 UTC, MrChico commented on _posts/2021-08-03-act-0.1.md
> +chain between this specification and an implementation of the spec in EVM bytecode.
or smth along these lines

2021-08-19 23:10 UTC, endorphin commented
This looks very nice. I read the coq section and offered some suggestions in  #8.

2021-08-25 23:38 UTC, kjekac requested changes
Just a bunch of nitpicks, rephrasings, spelling corrections and so on, nothing "big". The overall structure seems good. Still, I'm gonna read it all the way through once these changes have been included (or denied), in order to actually see and feel the flow instead of getting caught up in details.

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +knowledge. It has a built in analysis engine that can automatically prove properties about the
Afaik "built-in" is a proper adjective and at least to me the hyphen makes the sentence easier to parse.

```suggestion
knowledge. It has a built-in analysis engine that can automatically prove properties about the
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +While a lot of work still remains to be done before act can be used to verify properties on
Let's normalize treating Act as a proper name imo.

```suggestion
While a lot of work still remains to be done before Act can be used to verify properties of
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +extremely adverserial environment, and even a single oversight can easily result the loss of
```suggestion
extremely adverserial environment, and even a single oversight can easily result in the loss of
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +properties is enourmously valuable. Act grew out of the verification work carried out for multi
```suggestion
properties is enormously valuable. Act grew out of the verification work carried out for multi
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +language developed as a part of this process, incorporating many of the lessons learned along the
such hypertext
very WWW
wow

```suggestion
properties is enourmously valuable. Act grew out of the work of [verifying multi-collateral Dai](https://github.com/dapphub/k-dss/) and [Uniswap v2](https://github.com/dapp-org/k-uniswap-v2), and is a ground-up rewrite in Haskell of the [prototypical specification language](https://github.com/dapphub/klab/blob/master/acts.md) which was developed as a part of that process, incorporating many of the lessons learned along the
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +-> binary compiler output) are used to prove these properties down to the binary level.
I'm not familiar with SeL4 and its internal process, and am having trouble following here.

I presume that it first proves that the high-level spec has certain properties, and then? It compiles this spec to Haskell? And there exists some proof that the compilation from spec to Haskell preserves certain properties? (But presumably not all possible properties..?) And then the same thing happens again from Haskell to C and then finally to bytecode? Or am I misunderstanding?

Even if I got it right this may be worth clarifying since we use it as a pedagogical example.

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +Different tools and techniques have different strengths and weaknesses, and with Act we want to make
```suggestion
Different tools and techniques for formal verification have different strengths and weaknesses, and with Act we want to make
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +even state in the language accepted by an SMT solver.
```suggestion
analysis engine will usually be significantly faster and more convenient than manually constructing
a proof in a proof assistant like Coq, but the latter can prove the correctness of statements that
would be impossible to even state in the language accepted by an SMT solver.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +With Act as an intermediate language, we can combine and share knowledge from many different tools
```suggestion
With Act as an intermediate language, we can combine and share knowledge between many different tools
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +operators that are simply not expressible in a language like solidity.
```suggestion
the 256 bit integers available in the EVM allow, while others may require temporal operators or quantifiers, neither of which are expressible in a language like Solidity.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +properties, and combined with it's ability to export the specification into the Coq proof assistant
```suggestion
properties, and combined with its ability to export the specification into the Coq proof assistant,
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +we believe that it should be possible to state almost any property about a given specification.
```suggestion
we believe that it should be possible to express almost any property of a given specification.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +If you want to play around with the examples in this blogpost, you can checkout the
Really just a matter of taste I think? But the original text felt weird to me.

```suggestion
If you want to play around with the examples in this post, you can check out the
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +Act can currently be installed via [nix](https://nixos.org/guides/install-nix.html) with the
These suggestions are mutually exclusive. My opinion is that we should either treat "Nix" as a proper name or as a command.

```suggestion
Act can currently be installed via [Nix](https://nixos.org/guides/install-nix.html) with the
```
```suggestion
Act can currently be installed via [`nix`](https://nixos.org/guides/install-nix.html) with the
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +  value, and the conditions that must be satisfied in order for it to be applied.
```suggestion
A specification of a contract written in Act consists of a *constructor* and a set of *behaviours*:

- The *constructor specification* defines the structure of the contract's state, the initial value of
  the state, and a list of invariants that the contract should satisfy.

- Each *behaviour specification* determines how a contract method updates the state, the method's return
  value (if any), and any conditions that must be satisfied in order for the state update to be applied.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +A more detailed level language reference can be found [here](https://github.com/ethereum/act/blob/master/docs/act.md).
```suggestion
A more detailed high level language reference can be found [in the documentation](https://github.com/ethereum/act/blob/master/docs/act.md).
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +The types of Act consist of three basic primitives: Integers, Booleans and ByteStrings. Integers are
```suggestion
The types of Act consist of three basic primitives: Integers, Booleans and Bytestrings. Integers are
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +together with the constraint that the value fits into a `uintN`/`intN`.
```suggestion
together with the constraint that the value fits into a `uintN`/`intN`. If any
operation could over- or underflow this bound, the constraint will be unfulfilled
and the specification will fail to prove.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +As an example consider this specification of a trivial contract that adds two numbers and stores the result on chain:
I'm all for short paragraphs but these sentences really seem like they belong together? :)

```suggestion
Using conventional ABI types for typing also allows us to specify function signatures in a concise way.
As an example, consider this specification of a trivial contract that adds two numbers and stores the result on chain:
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +In more verbose terms, this specification would read:
```suggestion
Expressed in English and math, this specification would read:
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +The contract `Add` has a single state variable, named `result`, which is an integer s.t. `0 <= result < 2^256`.
I'm not opposed to jargon-abbreviations but let's at least type out the entire thing on the first usage? Luckily the next usage comes directly afterwards so its meaning should be easy to infer given a previous example.

```suggestion
The contract `Add` has a single state variable, named `result`, which is an integer such that `0 <= result < 2^256`.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +call to the contract `Add` with the signature `add(uint256,uint256)`, and `x` and `y`, will:
Any reason we don't include `x` and `y` in the signature, like so?:
```suggestion
call to the contract `Add` with the signature `add(uint256 x,uint256 y)` will:
```
Maybe signatures aren't formatted like that? In that case I suggest we write this instead:
```suggestion
call to the contract `Add` with the signature `add(uint256,uint256)`, with its respective arguments named `x` and `y`, will:
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +Two claims are generated for each behaviour, `Pass` and a `Fail`. The `Pass` claim states
```suggestion
Two claims are generated for each behaviour, `Pass` and `Fail`. The `Pass` claim states
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +will be updated according to the `storage` block, and the expected value will be returned. The
This may look like completely unnecessary but for a second I actually thought that the current text was referring to the [expected value of a random variable](https://en.wikipedia.org/wiki/Expected_value), so we may as well minimize any confusion.

```suggestion
will be updated according to the `storage` block, and the specified return value will, in fact, be returned. The
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +`interface` block (i.e. a concrete selector with abstract types), making the relevant assumptions
>i.e. a concrete selector with abstract types

what mean?

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +depending on whether the proof is a `Pass` or `Fail` kind, and then symbolically executing
For consistent disambiguation between "proof" and "claim".

```suggestion
depending on whether the claim is `Pass` or `Fail`, and then symbolically executing
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +This produces a tree of potential executions where each node in the tree is a potential branching
```suggestion
This produces a tree of potential executions where each node represents a potential branching
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +states of the contract after the execution of a single call.
```suggestion
point, and each leaf represents a possible final state of the contract after the execution of a single call.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +for a `Pass` proof we can check that storage has been updated as expected, and that the contents of
```suggestion
In the case of a `Fail` claim, we can then check that each leaf represents a state in which execution
has reverted, while for a `Pass` claim we can check that storage has been updated as expected, and that the contents of
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +the return buffer match that defined in the behaviour's `returns` block.
```suggestion
In the case of a `Fail` claim, we can then check that all leaves represent states in which execution
has reverted. Inversely, for a `Pass` claim we can check that in all leaves, storage has been updated as expected and the content of
the return buffer matches what was specified in the behaviour's `returns` block.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +We can represent this in act as:
```suggestion
We can represent this in Act as:
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +equivalence between the spec and the runtime bytecode:
```suggestion
equivalence of the spec and the runtime bytecode:
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +If we try to prove equivalence against a faulty implementation like the one below:
```suggestion
If we try to prove equivalence of the spec and a faulty implementation like the one below:
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +```
Especially without color coded output, this looks weird at first glance. Seeing `Successfully proved` on the last line as a lazy programmer, I would likely assume that everything is hunky dory. Maybe we'd like to add a final line of output which summarizes the individual outputs?

E.g. `dapp.sol does NOT satisfy simple.act. Failed to prove the Pass claim.`?

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +property:
```suggestion
properties:
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +- Contract level invariants (i.e. properties that are always true for every possible contract state)
This may seem like a nitpick but just a little bit above we literally talked about "states" in the sense of the actual execution. Invariants don't make any claim about those states, but are only concerned with the final states produced by `constructor`s and `behaviour`s.

```suggestion
- Contract level invariants (i.e. properties that are true in all possible poststates of the constructor, as well as in all possible pre- and poststates of any behaviours)
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +### Syntax
Just to make each section a bit shorter and more focused.

```suggestion
### Postcondition syntax
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +Invariants are defined in the `invariants` block in the constructor specification. Each invariant is
As above, more focus through shorter sections.

```suggestion

### Invariant syntax

Invariants are defined in the `invariants` block in the constructor specification. Each invariant is
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +Postconditions are defined at the behaviour level in the `ensures` block. All references to storage
```suggestion
Postconditions are defined in an optional `ensures` block of each `behaviour`. All references to storage
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +in an `ensures` block must to specify whether they talk about the variable's value in the pre- or
```suggestion
in an `ensures` block must specify whether they talk about the variable's value in the pre- or
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +a predicate that should hold for every possible contract state. Invariant predicates have access to
It feels to me like we need a technical term which is equivalent to "constructor or behaviour". I'm using "state transition" here since further up we described constructors as state defs and behaviours as transitions, but maybe there is something better?

```suggestion
a predicate that should hold between the execution of any state transitions. Invariant predicates have access to
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +not need to disambiguate storage references with `pre` and `post`.
```suggestion
contract state (as opposed to predicates in `ensures` blocks which have access to a pair of states),
it is neither necessary nor allowed to disambiguate storage references using `pre(x)` and `post(x)`
in invariant predicates.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +[SMT](https://en.wikipedia.org/wiki/Satisfiability_Modulo_Theories) based encoding of each behaviour
```suggestion
[SMT](https://en.wikipedia.org/wiki/Satisfiability_Modulo_Theories)-based encoding of each behaviour
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +all storage updates have occurred as defined in the `storage` block, and then ask it to find
```suggestion
When proving postcondition claims, it is quite uninformative to prove that they are satiable by *some*
variable configuration; there could still be many others which violate it. Instead, we attempt to violate
it and hope that we fail. We tell the solver to assume all preconditions as well as that
all storage updates have occurred as specified in the `storage` block. We then ask it to find
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +lead to a violation of the postcondition. If none can be found, then we have a proof that the
```suggestion
an assignment for the abstract variables in the spec (calldata, environment, and storage) that violates the postcondition. If none can be found, we have a proof that the
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +For the invariant claims, we attempt to construct an inductive proof. We first ask the solver to
```suggestion
Invariant claim are proved inductively. For the base case, we ask the solver to
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +poststate, if none can be found we have a proof of the base case. For the inductive step we
```suggestion
poststate. If none can be found, we have a proof of the base case.

For the inductive step, we
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +As an example consider the following specification of a highly simplified uniswap style [constant
```suggestion
As a larger and practical example, let's consider the following specification of a highly simplified Uniswap-style [constant
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +important safety property, if it is violated, an attacker will be able to execute a sequence of
```suggestion
important safety property – if it is violated, an attacker is able to execute a sequence of
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +If the `Amm` starts with `reserve0 == 2` and `reserve1 == 5000,000`, and `swap0` is called with `amt
```suggestion
If the `Amm` is in the state  `reserve0 == 2` and `reserve1 == 5000,000`, and `swap0` is called with `amt
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +333,333` is `999,999`, and in fact the product of the reserves has decreased slightly due to
```suggestion
333,333` is `999,999`, meaning that the product of the reserves has decreased slightly due to
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +the `x == 7` branch in `j()` is still reachable.
```suggestion
the `x == 7` branch in `h()` is still reachable.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +invariant of this form that holds over the full transition system.
```suggestion
We can fix this by strengthening the invariant to make the `x == 7` branch unreachable. Specifically, the
weakest invariant that does hold over the full transition system (while remaining on the same form as the
original) is `x < 7`. The strongest is `x < 3`.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +A proof assistant provides tools that help with the construction of proof.  Coq, in particular, is
```suggestion
A proof assistant provides tools that help with the construction of proofs. Coq, in particular, is
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +The requirements for proof in a system like Coq, Isabelle, or Lean are quite strict. These tools
```suggestion
The requirements on proofs in a system like Coq, Isabelle, or Lean are quite strict. These tools
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +been found in Coq's and other system's kernels, proof in these systems is generally quite strong
```suggestion
The verification of these proofs is performed in a minimal and well-audited kernel. Although occasionally bugs have
been found in Coq's and other systems' kernels, a proof in these systems is generally quite strong
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +### A Brief Introduction to Proof in Coq
```suggestion
### A Brief Introduction to Proofs in Coq
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +Coq is a complex system with a non trivial learning curve, while a full tutorial on programming in
```suggestion
Coq is a complex system with a steep learning curve, and while a full tutorial on programming in
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +thorough introduction the books [Software Foundations](https://softwarefoundations.cis.upenn.edu/)
```suggestion
thorough introduction, the books [Software Foundations](https://softwarefoundations.cis.upenn.edu/)
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +fields of formal logic and proof.
```suggestion
fields of formal logic and proofs.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +a tactics language for the construction of proof (Ltac), and a "vernacular" for interaction with the
```suggestion
a tactics language for the construction of proofs (Ltac), and a "vernacular" for interaction with the
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +vernacular command, even if they are not in fact recursive. Coq's `Inductive` is analagous to
Consistent language.

```suggestion
vernacular command, even if they are not in fact inductive. Coq's `Inductive` is analagous to
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +`n` produces the representation of the number `n + 1` (the Successor). To give a concrete example
```suggestion
`n` produces the representation of the number `n + 1` (`S` as in "successor"). To give a concrete example,
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +Lets continue by defining addition over our `nat` type:
```suggestion
Let's continue by defining addition over our `nat` type:
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +might think of this definition as "unwrapping" the applications of `S`.
```suggestion
might think of this definition as "unwrapping" each application of `S` from the first argument until
we reach its `O`. Then we start wrapping the second argument in the same number of `S`s.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +### Expresiveness
```suggestion
### Expressiveness
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +The best way to understand the system is to run the software your self, and play around with the
```suggestion
The best way to understand the system is to run the software yourself, and play around with the
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +  intros n. simpl. reflexivity.
`intros n.` is never explained.

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +Next we have `exp0`, which defines how state is updated by the `exp` behaviour, and `Exponent0`
```suggestion
Next we have `exp0`, which defines how the state is updated by the `exp` behaviour, and `Exponent0`
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +value of `e` in `s` is `1` then the result variable `r` in `s` has the value of `b` from `base`
```suggestion
value of `e` in `s` is `1`, then `r` in `s` is equal to `b` from `base`
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +We must first define a helper fact `pow_pred` that states simply that given two integers `a`
```suggestion
We must first define a helper fact `pow_pred` which simply states that given two integers `a`
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +and `e`, if `e` is greater than `0` then `a * a ^ (e -1)` is the same as `a ^ e`. This fact is
```suggestion
and `e`, if `e` is greater than `0` then `a * a ^ (e - 1)` is equal to `a ^ e`. This fact is
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +1. A proof of this property is beyond the reach of any automated tool available today
```suggestion
1. A proof of this property is beyond the reach of any automated tool available today.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +Act is designed to be simple and explicit. While this supports automated analysis based on the act
```suggestion
Act is designed to be simple and explicit. While this supports automated analysis based on the Act
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +as a set of act specifications. This should allow for fast iteration on the implementation, while
```suggestion
as a set of Act specifications. This should allow for fast iteration on the implementation, while
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +allowing for high level analysis of that implementation with Coq and the Act smt backend.
```suggestion
keeping the barrier low to at any time performing high-level analyses using Coq or the Act SMT backend.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +this out we encountered a fundamental issue: while act specs are expressed in terms of unbounded
```suggestion
represents our first attempt at a bytecode level proof engine for Act. Unfortunately while building
this out we encountered a fundamental issue: while Act specs are expressed in terms of unbounded
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +equivalence between a given bytecode object and a set of act specs requires conversions from
```suggestion
equivalence between a given bytecode object and a set of Act specs requires conversions from
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +directly from the bytecode and are therefore "correct by construction". Even in the case where specs
```suggestion
An automated spec generation engine would allow us to sidestep this issue; since the specs would be
generated directly from the bytecode they are *correct by construction*, so it would be unnecessary
to prove equivalence between bytecode and specs. Even in the case where specs
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +`bv_to_int` and `int_to_bv` smt operations.
Is my description of the technical situation still correct with these changes? We would compare the hand-written spec to one that had been generated by hevm?

```suggestion
directly from the bytecode and are therefore "correct by construction". Even when we encounter a
hand-written spec, it would only be necessary to prove equivalence between that and a generated
spec, both of which would be written in terms of integers.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +or `bytes`), the various proof backends do not currently support proof involving these types.
```suggestion
or `bytes`), the various proof backends do not currently support proofs involving these types.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +proof backends.
```suggestion
its proof backends.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +development.  As we saw in the `AMM` example above, numeric error introduced by precision loss can
```suggestion
Understanding the impact of rounding errors in a smart contract is a critical task for secure
development.  As we saw in the `AMM` example above, a numeric error introduced by precision loss can
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +There are generally two properties of interest:
```suggestion
There are generally two properties of rounding errors which are of interest:
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +result of the calculation over the real numbers and it's rounded result when expressed over the
```suggestion
result of the calculation over the real numbers and its rounded result when expressed over the
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +For a manual example of a similar analysis, see the [uniswap v1
```suggestion
For an example of such an analysis performed manually, see the [Uniswap v1
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +eth or token transfer, or for more complex actions (e.g. delegation of control for a flash loan).
Choose either one of these imo.
```suggestion
ether or token transfer, or for more complex actions (e.g. delegation of control for a flash loan).
```
```suggestion
ETH or token transfer, or for more complex actions (e.g. delegation of control for a flash loan).
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +[here](https://github.com/ethereum/act/issues/18).
```suggestion
We intend to introduce language constructs and verification routines which will allow specifying
and proving properties of such contracts. For more information, we have an
[issue with early ideas](https://github.com/ethereum/act/issues/18).
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +specification and proof for loop invariants.
```suggestion
(e.g. in numeric routines). We intend to introduce syntax and verification extensions which allow
for specification and proving of loop invariants.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +[#2](https://github.com/ethereum/act/issues/2), [#3](https://github.com/ethereum/act/issues/3).
```suggestion
For those interested, we have some [early thoughts](https://github.com/ethereum/act/issues/2) and [discussion](https://github.com/ethereum/act/issues/3) on the specifics of how to encode loop invariants.
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +framework to allow for complex economic analysis. We believe that Act has some unique advantages
```suggestion
Act could be extended with a backend that exports to – possibly even integrates
with – an agent-based modelling framework, to allow for complex economic
analysis. We believe that Act has some unique advantages
```

2021-08-25 23:38 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +which contains a model of the above act specification in Coq:
```suggestion
which contains a model of the above Act specification in Coq:
```

2021-08-26 11:18 UTC, d-xo commented on _posts/2021-08-03-act-0.1.md
> +Alternatively, they can be thought of an initial state and a set of state transitions, determining
```suggestion
Alternatively, they can be thought of as an initial state and a set of state transitions, determining
```

2021-08-26 11:18 UTC, d-xo commented on _posts/2021-08-03-act-0.1.md
> +`interface` block (i.e. a concrete selector with abstract types), making the relevant assumptions
so if we wanted to symbolically execute a method with the signature `add(uint, uint)`, we fill the calldata buffer in the EVM state with a buffer that looks like this:

```
function selector (concrete, e.g. `0x123456`) | symbolic uint256 | symbolic uint 256
```

Not sure how to best express that or if it's simply too much detail?

2021-08-26 11:18 UTC, d-xo commented on _posts/2021-08-03-act-0.1.md
> +-> binary compiler output) are used to prove these properties down to the binary level.
So I'm not deeply familiar with the SeL4 proof chain, but what I know is based on skimming these two papers: 

- http://www.sigops.org/s/conferences/sosp/2009/papers/klein-sosp09.pdf
- https://ts.data61.csiro.au/publications/nicta_full_text/6449.pdf

Which show that the refinement chain looks something like this down to the C semantics:

![image](https://user-images.githubusercontent.com/6689924/130928636-de51e1f0-c669-45b8-b219-771cfe4006da.png)

And like this from C to binary:

![image](https://user-images.githubusercontent.com/6689924/130928722-915bfaeb-8c1d-4668-88de-116d445e3868.png)

So as I understand it the high level spec is written in issabelle and various properties are proven against this. Then there is a refinement stage (again in issabelle), proving equivalence between the high level spec and the specification written in haskell (which has been imported into issabelle), a further (issabelle based) refinement step proves equivalence between the haskell spec and the C implementation (where the C implementation has been imported into issabelle via some lightweight C semantics), and finally there is a C -> binary refinement stage run using some custom SMT based analyis tooling.

2021-08-26 11:18 UTC, d-xo commented on _posts/2021-08-03-act-0.1.md
> +for a `Pass` proof we can check that storage has been updated as expected, and that the contents of
hmmmmm, I think I was trying to make a seperation between the claim (i.e. the act AST), and the procedure by which we would verify the correctness of that claim (the proof). Do you think the distinction doesn't make sense?

2021-08-26 11:18 UTC, d-xo commented on _posts/2021-08-03-act-0.1.md
> +```
very good idea

2021-08-26 11:18 UTC, d-xo commented on _posts/2021-08-03-act-0.1.md
> +all storage updates have occurred as defined in the `storage` block, and then ask it to find
maybe worth splitting out into a seperate paragraph talking about how SMT proofs work, with a little bit of into into what an SMT solver actually does?

2021-08-26 11:18 UTC, d-xo commented on _posts/2021-08-03-act-0.1.md
> +value of `e` in `s` is `1` then the result variable `r` in `s` has the value of `b` from `base`
```suggestion
value of `e` in `s` is `1`, then the result variable `r` in `s` is equal to `b` from `base`
```

2021-08-26 11:18 UTC, d-xo commented on _posts/2021-08-03-act-0.1.md
> +  intros n. simpl. reflexivity.
I was kinda trying not to get too into the weeds with the proof, I think intros is hard to explain without a running instance of proof general or similar? Do you have a suggestion?

2021-08-26 11:36 UTC, kjekac requested changes
Somehow this suggestion was marked as outdated even though the misspelling hasn't been corrected.

2021-08-26 11:36 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +properties is enourmously valuable. Act grew out of the work of [verifying multi-collateral Dai](https://github.com/dapphub/k-dss/) and [Uniswap v2](https://github.com/dapp-org/k-uniswap-v2), and is
```suggestion
properties is enormously valuable. Act grew out of the work of [verifying multi-collateral Dai](https://github.com/dapphub/k-dss/) and [Uniswap v2](https://github.com/dapp-org/k-uniswap-v2), and is a ground-up rewrite in Haskell of the [prototypical specification language](https://github.com/dapphub/klab/blob/master/acts.md) which was developed as a part of that process, incorporating many of the lessons learned along the
```

2021-08-26 11:39 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +for a `Pass` proof we can check that storage has been updated as expected, and that the contents of
Ah, hmm. We could probably make that distinction instead but iirc a bit further up both `Pass` and `Fail` were referred to as "claims", which was why I made these suggestions for consistency; I can accept most terminologies as long as we pick one and stick with it as far as possible.

But if I were dictator I would prefer to only call things proofs when it is certain that they are valid; until it is, they are unproven claims. So I personally still vote for "claims" here. But again, I'm completely ok with your distinction too.

2021-08-26 11:41 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +`interface` block (i.e. a concrete selector with abstract types), making the relevant assumptions
Yes, too much detail imo, especially since it's of no consequence to anything else we discuss.
```suggestion
`interface` blocks, as well as making the relevant assumptions
```

2021-08-26 12:13 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +all storage updates have occurred as defined in the `storage` block, and then ask it to find
Yes, agreed.

2021-08-26 12:26 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +various tactics.  In this case the goal is simple enough; Coq is able to simplify `plus O n` into
```suggestion
various tactics.  In this case the goal is simple enough; once we've specified that the proof will be on `n`, Coq is able to simplify `plus O n` into
```

2021-08-26 12:27 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +  intros n. simpl. reflexivity.
I have no idea, I don't know what it does or how complicated it is. I was taking this blog post as an opportunity to learn some Coq and understand our Coq backend, so it felt a bit odd that it was the only part of this particular proof that wasn't referenced at all in the explanation.

But I just skimmed some explanation of its meaning and from what I understand it's necessary because we have `forall` in the theorem? Kind of like saying "now we're gonna work with this particular variable"? If so, how about [this suggestion](https://github.com/ethereum/fv-blog/pull/7/files#r696579087)?

2021-08-26 13:56 UTC, d-xo commented on _posts/2021-08-03-act-0.1.md
> +has reverted. Inversely, for a `Pass` claim we can check that in all leaves, storage has been updated as expected and the content of
```suggestion
In the case of a `Fail` claim, we can then check that each leaf represents a state in which execution
has reverted, while for a `Pass` claim we can check that storage has been updated as expected, and that the contents of
```

2021-08-26 17:53 UTC, kjekac approved these changes

2021-08-26 18:04 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +-> binary compiler output) are used to prove these properties down to the binary level.
Sorry, I may have been unclear. I wasn't really asking about how SeL4 works, I was just saying that as-is, I think this part of the text is pretty muddy if one is unfamiliar with the inner workings of SeL4, which I suspect most of our readers are.

Do you think it's pedagogically helpful to explicitly refer to the mechanics of SeL4? I don't think so. I think the text would be easier to follow if we simply described our architecture, and then we can score some credibility by mentioning that well-established tools (such as SeL4) essentially solve the issue in the same way.

Thoughts?

2021-08-27 07:47 UTC, d-xo commented on _posts/2021-08-03-act-0.1.md
> +-> binary compiler output) are used to prove these properties down to the binary level.
```suggestion
successive refinement steps are used to prove these properties down to the binary level ([1](http://www.sigops.org/s/conferences/sosp/2009/papers/klein-sosp09.pdf)[2](https://ts.data61.csiro.au/publications/nicta_full_text/6449.pdf))
```
Ah I see, yes I think you're correct. Maybe something like this?

2021-08-27 19:45 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +```
As per the new PR:

````suggestion
```
< act hevm --spec src/simple.act --soljson out/dapp.sol.json
checking postcondition...
Calldata:
0x60fe47b100000000000000000000000000000000000000000000000000000000000007d0
Caller:
0x0000000000000000000000000000000000000000
Callvalue:
0
Failed to prove set(Pass)
checking postcondition...
Q.E.D.
Successfully proved set(Fail), 2 cases.
==== FAILURE ====
1 out of 2 claims unproven:

1	Failed to prove set(Pass)
```
````

2021-08-27 19:54 UTC, kjekac commented on _posts/2021-08-03-act-0.1.md
> +Successfully proved set(Fail), 2 cases.
```suggestion
Successfully proved set(Fail), 2 cases.
==== SUCCESS ====
All behaviours implemented as specified ∎.
```

2021-08-31 08:35 UTC, d-xo commented
@leonardoalt @MrChico Im going to publish this afternoon unless there are any last comments

2021-08-31 09:13 UTC, MrChico commented on _posts/2021-08-03-act-0.1.md
> +contains much extraneous detail (e.g. overflow checks, bitmasks in storage access routines, function
also abi encoding/decoding

2021-08-31 09:17 UTC, leonardoalt reviewed
Amazing write up!

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +statment is untrue, and if none are found, we can infer the truth of the original statement. As an
```suggestion
statement is untrue, and if none are found, we can infer the truth of the original statement. As an
```

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +Proof in an SMT solver can sometimes feel a little "backwards", instead of asking the solver to
Maybe we should just say SMT-based program verification is often done by contradiction here? I feel like the `backwards` idea is a bit vague.

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +assignment for the abstract variables in the spec (calldata, environment, and storage) that violates
```suggestion
assignment for the symbolic variables in the spec (calldata, environment, and storage) that violates
```
?

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +If the `Amm` is in the state  `reserve0 == 2` and `reserve1 == 5000,000`, and `swap0` is called with `amt
```suggestion
If the `Amm` is in the state  `reserve0 == 2` and `reserve1 == 500,000`, and `swap0` is called with `amt
```

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +A proof assistant provides tools that help with the construction of proof.  Coq, in particular, is
It still says `proof` instead of `proofs`

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +The requirements for proof in a system like Coq, Isabelle, or Lean are quite strict. These tools
Same here

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +### A Brief Introduction to Proof in Coq
Same here

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +been found in Coq's and other systems' kernels, a proof in these systems is generally quite strong
```suggestion
been found in Coq's and other systems' kernels, a proof in these systems is generally a quite strong evidence of correctness.
```

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +fields of formal logic and proof.
Same here

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +a tactics language for the construction of proof (Ltac), and a "vernacular" for interaction with the
Same here

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +kernel.  Lets start with the very basics: defining the natural numbers and proving something about
```suggestion
kernel.  Let's start with the very basics: defining the natural numbers and proving something about
```

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +Now we're ready to prove something! Lets prove that `0 + n == n`:
```suggestion
Now we're ready to prove something! Let's prove that `0 + n == n`:
```

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +`bv_to_int` and `int_to_bv` smt operations.
```suggestion
`bv_to_int` and `int_to_bv` SMT operations.
```

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +### Automated Checks for Spec Integrity
```suggestion
### Automated Checks of Spec Integrity
```
?

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +- Collisions in mapping assignments ([#111](https://github.com/ethereum/act/issues/111))
The links are all `111` but the tags 109, 110, and 111.

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +or `bytes`), the various proof backends do not currently support proof involving these types.
Same here (proofs)

2021-08-31 09:17 UTC, leonardoalt commented on _posts/2021-08-03-act-0.1.md
> +guarantee that the simulation accurately models the deployed implementation.
Maybe end with something like
```
Contributions are always welcome, please report bugs on GH, etc
```
?

2021-08-31 11:20 UTC, merged